### ISSUE TITLE
Enhancement regarding status filter field to include "Challenged"

### ISSUE THREAD

**Issue by PresenceNumerique** [1Hive/gardens-ui#252]
For now it seems one cannot filter "Challenged" items on the list.

![image](https://user-images.githubusercontent.com/46331204/109992109-3c04ec80-7d0b-11eb-8869-6f2db32d8271.png)

It would be smoother if we could have this option.

**Comment by tmoutinho** [comment]
Hey @0xGabi, I added this status Challenged in this PR https://github.com/1Hive/gardens-ui/pull/790
