### ISSUE TITLE
Suggestion: Proposal created success message

### ISSUE THREAD

**Issue by fabriziovigevani** [1Hive/gardens-ui#355]
As suggested by @GriffGreen, It would be nice to have some final success screen when creating a proposal with some confetti animation as well perhaps

**Comment by kamikazebr** [comment]
Like thtat? https://www.cssscript.com/demo/confetti-falling-animation/

**Comment by kamikazebr** [comment]
https://codepen.io/marcobiedermann/pen/ExvvyLQ Using React, more beautiful and integrated in the button

**Comment by fabriziovigevani** [comment]
Yes something like this! :) I like the React one better

**Comment by 0xGabi** [comment]
We can also integrate on the final step of the onboarding. Do you want to give it a shoot @kamikazebr?

**Comment by kamikazebr** [comment]
Hi @0xGabi! Yes i want try, i just need some guide to setup the enviroment, i'll clone it and run to find the files need to change.

**Comment by kamikazebr** [comment]
PR to Onboarding Confetti https://github.com/1Hive/gardens-ui/pull/729

I saw now, need on proposal too, i'll check that too.
