### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by fabriziovigevani** [1Hive/gardens-ui#418]
https://www.figma.com/file/w97oARETFFr4WyApvdqV5E/%F0%9F%8C%91-Honey-Pot-Dark-Mode-V2?node-id=0%3A1

**Comment by kamikazebr** [comment]
https://www.joshwcomeau.com/react/dark-mode/
Amazing article about how implement it. It works to React too.

**Comment by 0xGabi** [comment]
close with #649
