### ISSUE TITLE
can't add context to decision votes

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/gardens-ui#750]
testing on `gardens staging` 

I'm creating decision votes to change the parameters of my test DAO - when I create a vote using the EVM Executor there are no fields for me to add a description to my vote nor is there anyway for for a DAO member to verify exactly what I'm proposing to do. Suggest: 

1. Add a text input field for users to describe their vote 
2. output the evm function/script proposing to be ran on the UI or in a link attached to the proposal so users can verify the actual intention of the decision vote

![image](https://user-images.githubusercontent.com/67759413/146773239-6d3b99fa-7a0d-4824-bb1d-7291b90e0911.png)

### no idea what he's proposing to do - why would I vote for this? 
![image](https://user-images.githubusercontent.com/67759413/146773374-53450810-1a50-4c6c-ab47-2c0bb5b0ba5b.png)

**Comment by rperez89** [comment]
closed with <https://github.com/1Hive/gardens-ui/pull/849>
