### ISSUE TITLE
my decision votes to modify decision voting are unexecutable! 

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/gardens-ui#752]
on gardens staging  with brave browser

I created and passed a series of decision votes using the EVM executor (Internal) to modify our tao (decision) voting settings 
https://gardens-staging.1hive.org/#/xdai/garden/0x2050eabe84409e480ad1062001fdb6dfbc836192

all of them passed but when i try to execute them they fail! 
https://blockscout.com/xdai/mainnet/tx/0xa5990cc1d26fc0660185d8cd96e85ed055d069ca10ee088ef916f54fde19a282
https://blockscout.com/xdai/mainnet/tx/0x90f4ce0e7ff73ea9284052f5693fbddb4f539c2ff10bb4d5e98c2660db0686be
https://blockscout.com/xdai/mainnet/tx/0xa543b7236903662645e50fb23f8498e54131d073a82b3ebb9bae826c601c8032

what did I do wrong?

**Comment by 0xGabi** [comment]
I am closing this one as it was already figured it out. Instead I am creating a new issue to include a documentation section about the missing permissions by default: https://github.com/1Hive/gardens/issues/506
