### ISSUE TITLE
can't load deposit manager

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/gardens-ui#773]
currently on `staging` with clean cache and cookies and brave browser 

from my gardens main view I try to access my deposit manager and I am thrown an error and prevented from reaching the deposit manager screen. 

![image](https://user-images.githubusercontent.com/67759413/148294737-543a686d-5103-432b-8efc-56a6bd7275f7.png)

**Comment by tmoutinho** [comment]
Hey @divine-comedian I have fixed this in https://github.com/1Hive/gardens-ui/pull/782 . Just waiting for review on this.

**Comment by tmoutinho** [comment]
The PR that fixes this as been merged. Can you please confirm its fixed @divine-comedian ? Thank you.

**Comment by divine-comedian** [comment]
looks great! Issue seems to be resolved. 
![image](https://user-images.githubusercontent.com/67759413/149645140-8fb91de5-b0ac-47ce-b884-3bee58c7a0fe.png)

**Comment by tmoutinho** [comment]
Good! Will close this issue then. 🙂
