### ISSUE TITLE
Gardens list keeps re-rerendering after a filter is selected

### ISSUE THREAD

**Issue by tmoutinho** [1Hive/gardens-ui#776]
The list is always fetching when a filter is selected.

**Comment by tmoutinho** [comment]
[Uploading... Gravação do ecrã 2022-01-06, às 09.53.28.mov]

**Comment by tmoutinho** [comment]
https://images.zenhubusercontent.com/273752093/a4361ea7-5ab5-4e42-a93e-bbc6280e5fa8/gravac_a_o_do_ecra__2022_01_06__a_s_09_53_28.mov

**Comment by 0xGabi** [comment]
done with #777
