### ISSUE TITLE
forum post integration on proposals is BROKEN

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/gardens-ui#791]
currently  this issue is on `PRODUCTION` 

brave browser w/ clean cache and cookies 

I'm currently on the GIV garden browsing proposals - it seems the forum integration feature is definitely not working as intended

![image](https://user-images.githubusercontent.com/67759413/149341546-899d5818-9ffc-4303-824b-afe2f5e0d695.png)

Irrelevant forum posts from the wrong forum before the proposal was made?? 

![image](https://user-images.githubusercontent.com/67759413/149341623-51e7ce56-a78f-44ca-bad7-ff8dbeac91ee.png)

Broken link to the wrong forum?? (should be pointing to forum.giveth.io) 

This is currently live on the main deployment of Gardens.

**Comment by 0xGabi** [comment]
This was already fixed
