### ISSUE TITLE
Challenge requirements and deposit manager modals not consistent with blockchain state

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens-ui#826]
- [ ] The challenge requirements modal do not validate the locked deposits right:

![Screenshot_from_2022-02-16_10-50-28](https://user-images.githubusercontent.com/9082013/154279068-390ccb6e-8f4b-411a-a19b-424a5db76f3e.png)

---

The following point could be related to the same root cause as above. 
- [ ] The deposit manager modal does not validate requirements right:
	- `approve` step is omitted when needed

**Comment by kamikazebr** [comment]
Which should be the correct behaviour?

**Comment by 0xGabi** [comment]
Hey @kamikazebr here I share a video with a bit more context on the second point: https://discord.com/channels/698287700834517064/754870015357878304/953654135046144000

**Comment by rperez89** [comment]
@0xGabi after reviewing the code the amount needed to challenge a proposal needs to be on the challenger wallet and not on the staking manager.
The second issue was solved here #844

**Comment by 0xGabi** [comment]
You are right! Maybe we can update the text message to make that clear?
