### ISSUE TITLE
Show APR of unipool rewards

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens-ui#836]
Show APR% of "vote farming" (i.e. wrapped token rewards).  The APR is easy to calculate: divide the amount last sent to the 30 day rewards pool contract (in Bright DAO's case https://blockscout.com/xdai/mainnet/tx/0x646ff59a318c5508345125844c6470119b23d7a941722a98e8c53236137fa7f7/ = 50,000 Bright) by the wrapped supply and multiply by 12.   So right now, it's ( 50,000 / 1,420,712 ) * 12 = 42.2% APR

**Comment by lkngtn** [comment]
I took a look at this because I thought it might simple enough for me to take and had a few questions:

1. The example calculation depends on the most recent transaction to get the total reward amount, however this does not seem practical as we can’t easily read this transaction amount directly from the unipool contract. 
	* I propose that instead we should be able to calculate the APR using the `rewardRate` * `DURATION`  which should give us the reward amount (in Wei units) that is distributed over the duration. 
	* It appears that the `DURATION` constant is hardcoded at 30 days, so we can then multiply that by 12 to get a yearly projection of rewards, and divide that by the `totalSupply` to get a projected APR. 

2. Once we have the value where do we want to show it?

**Comment by 0xGabi** [comment]
Hey sounds great, I am assigning it to you.

About your questions:

1. I agree. Your proposed solution for the calculation is more accurate as well because have into consideration the `leftoverReward`. Doing a review of the `Unipool` contract I saw another alternative we have is using the [`rewardPerToken`](https://github.com/1Hive/unipool/blob/de057776f8a307b5d1de7e284213c0b2dc2dece1/contracts/Unipool.sol#L69-L81) method. And then multiply by `DURATION * 12`.
2. I am not convinced. We probably want it on the carousel component. Something like:
<img width="352" alt="Screen Shot 2022-03-18 at 5 42 17 PM" src="https://user-images.githubusercontent.com/9082013/159080709-a7b1ef0f-cf6f-4741-a955-f95a1a526ad1.png">

**Comment by lkngtn** [comment]
I created a draft PR implementing the APR calculation. 

However, as far as how to display it, I'm also not really sure the best way to go about it either. It feels a bit weird to me to put a metric inside a button label, and if we keep the style the same it ends up looking pretty cramped:

![image](https://user-images.githubusercontent.com/4986634/159102743-bb92ca5f-13a1-463f-8812-035046b6f288.png)

I also am not sure we should assume "sane" APR values in the single or double digits, It might make sense for a Garden to have really high rewards when they are just getting started as a sort of early adopter incentive, so the label could potentially be 1 or 2 more characters than that if we see "degen" APR values. 

I was thinking another approach might be to show it with the other Metrics like token price and total support, but not sure exactly what that would look like.

**Comment by tmoutinho** [comment]
IMO that info should not be in the button but in the card itself. But it's an important info for sure.

**Comment by rperez89** [comment]
> The concerns about having it on the button make lot of sense. I am not sure either about having it on the Metrics. What you think about an info box on top of the carousel? 🤔
> 
> I'll share the issue with the rest of the team and Adam to have more eyes.

i was thinking in having t the APR as the first  carousel item, what do you think?  if not as a box on top of the carousel as you suggested

**Comment by 0xGabi** [comment]
I like that idea, we can give it a try!

**Comment by pglavin2** [comment]
It would be cool if the icon at the top changed (on the wrap carousel item) when the Garden had active rewards for wrapping tokens, with the APR % next to it. Something like this:

![wrapped rewards](https://user-images.githubusercontent.com/9218761/159373564-d967cbc8-3413-4534-8a94-b48e6afd8ac1.png)

Then if the Garden didn't have wrapping rewards or the rewards had run out then it would look like it does today.

**Comment by lkngtn** [comment]
Updated my PR #843 to add the APR metric to the wrap card inline with the icon but not sure how to get the vercel preview to deploy. I'm also not sure where the icon @pglavin2 used in that image came from, so I kept the original icon for now but having it change to something more exciting when there is a reward seems like a good idea.

**Comment by kamikazebr** [comment]
> e vercel preview to deploy.

@lkngtn  You can ping me or @reznord to authorize it.

You need get inside the Gardens Swarm and open PR direct in that repo so you dont need get autorization to deploy in vercel.

And maybe it stopped deploy because you need resolve a conflict.

**Comment by 0xGabi** [comment]
close with #843
