### ISSUE TITLE
Fix(onboarding): specify the image size on the add profile section of the onboarding

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/gardens-ui#837]

**Comment by kamikazebr** [comment]
Its related to https://github.com/1Hive/gardens-ui/pull/848/files#?

**Comment by LPX55** [comment]
> Its related to https://github.com/1Hive/gardens-ui/pull/848/files#?

Yes, that was the intent. Not sure if the scope was properly understood and implemented as wished.

**Comment by kamikazebr** [comment]
@LPX55 Go to 1Hive Discord and Gardens Swarm.

**Comment by kamikazebr** [comment]
Closing it
